from utils import generate_image_pyramid,nms,adjust_boxes,square_boxes,load_image,iou,bbox_regression_target
import cv2
import numpy as np

# ---  Inference Functions for each network ---

def pnet_inference_function(
    image,
    pnet_model,
    min_size=12,
    scale_factor=0.709,
    cls_threshold=0.6,
    nms_threshold=0.5,
):
    """
    Performs FCN P-Net inference on an image pyramid.
    image: Input image (H, W, 3) np.uint8.
    pnet_model: Trained Keras P-Net model.
    min_size: Minimum face size to detect.
    scale_factor: Scaling factor for image pyramid.
    cls_threshold: Classification confidence threshold.
    nms_threshold: IoU threshold for NMS.
    Returns: Refined bounding boxes and their scores.
    """
    origin_h, origin_w, _ = image.shape
    image_pyramid = generate_image_pyramid(image, min_size=min_size, scale_factor=scale_factor)

    all_boxes = []
    all_scores = []

    stride = 2 # As per original MTCNN P-Net
    receptive_field_size = 12 # Receptive field of the P-Net output

    for scaled_image in image_pyramid:
        scale_h, scale_w, _ = scaled_image.shape

        input_img = (scaled_image.astype(np.float32) - 127.5) / 127.5
        input_img = np.expand_dims(input_img, axis=0)

        cls_prob_map, bbox_pred_map = pnet_model.predict(input_img, verbose=0)

        cls_prob_map = cls_prob_map[0]
        bbox_pred_map = bbox_pred_map[0]

        scores = cls_prob_map[:, :, 1].flatten()
        valid_indices = np.where(scores > cls_threshold)[0]

        if len(valid_indices) == 0:
            continue

        scores = scores[valid_indices]
        rows, cols = np.unravel_index(valid_indices, cls_prob_map[:,:,1].shape)

        x1_base = cols * stride
        y1_base = rows * stride
        x2_base = x1_base + receptive_field_size
        y2_base = y1_base + receptive_field_size

        proposals = np.stack([x1_base, y1_base, x2_base, y2_base], axis=1)

        bbox_reg_deltas = bbox_pred_map[rows, cols]

        adjusted_proposals = adjust_boxes(proposals, bbox_reg_deltas)

        keep = nms(adjusted_proposals, scores, nms_threshold, method='union')
        if len(keep) == 0:
            continue

        filtered_boxes_scale = adjusted_proposals[keep]
        filtered_scores_scale = scores[keep]

        original_coords_boxes = filtered_boxes_scale.copy()
        original_coords_boxes[:, 0] = original_coords_boxes[:, 0] / scale_w * origin_w
        original_coords_boxes[:, 1] = original_coords_boxes[:, 1] / scale_h * origin_h
        original_coords_boxes[:, 2] = original_coords_boxes[:, 2] / scale_w * origin_w
        original_coords_boxes[:, 3] = original_coords_boxes[:, 3] / scale_h * origin_h

        all_boxes.append(original_coords_boxes)
        all_scores.append(filtered_scores_scale)

    if len(all_boxes) == 0:
        return np.array([]), np.array([])

    all_boxes = np.vstack(all_boxes)
    all_scores = np.concatenate(all_scores)

    keep_final = nms(all_boxes, all_scores, nms_threshold, method='union')
    final_boxes = all_boxes[keep_final]
    final_scores = all_scores[keep_final]

    final_boxes = square_boxes(final_boxes)

    final_boxes[:, 0] = np.clip(final_boxes[:, 0], 0, origin_w - 1)
    final_boxes[:, 1] = np.clip(final_boxes[:, 1], 0, origin_h - 1)
    final_boxes[:, 2] = np.clip(final_boxes[:, 2], 0, origin_w - 1)
    final_boxes[:, 3] = np.clip(final_boxes[:, 3], 0, origin_h - 1)

    valid_indices = (final_boxes[:, 2] > final_boxes[:, 0]) & (final_boxes[:, 3] > final_boxes[:, 1])
    final_boxes = final_boxes[valid_indices]
    final_scores = final_scores[valid_indices]

    return final_boxes, final_scores

def rnet_inference_function(
    image,
    rnet_model,
    pnet_proposals,
    rnet_input_size=(24, 24),
    cls_threshold=0.7,
    nms_threshold=0.7
):
    """
    Performs R-Net inference on proposals generated by P-Net.

    Args:
        image: Original input image (H, W, 3) np.uint8.
        rnet_model: Trained Keras R-Net model.
        pnet_proposals: Bounding box proposals from P-Net (Nx4 array).
        rnet_input_size (tuple): Expected input size for R-Net (height, width).
        cls_threshold (float): Classification confidence threshold.
        nms_threshold (float): IoU threshold for NMS.

    Returns:
        Refined bounding boxes and their scores from R-Net.
    """
    if pnet_proposals.shape[0] == 0:
        return np.array([]), np.array([])

    img_h, img_w, _ = image.shape
    rnet_input_images = []
    valid_proposals = []

    for bbox in pnet_proposals:
        x1, y1, x2, y2 = bbox.astype(int)

        x1 = np.clip(x1, 0, img_w - 1)
        y1 = np.clip(y1, 0, img_h - 1)
        x2 = np.clip(x2, 0, img_w - 1)
        y2 = np.clip(y2, 0, img_h - 1)

        if x2 <= x1 or y2 <= y1:
            continue

        cropped_img = image[y1:y2, x1:x2]
        if cropped_img.shape[0] == 0 or cropped_img.shape[1] == 0:
            continue

        resized_img = cv2.resize(cropped_img, rnet_input_size, interpolation=cv2.INTER_AREA)
        normalized_img = (resized_img.astype(np.float32) - 127.5) / 127.5

        rnet_input_images.append(normalized_img)
        valid_proposals.append(bbox)

    if not rnet_input_images:
        return np.array([]), np.array([])

    rnet_input_images = np.array(rnet_input_images)
    valid_proposals = np.array(valid_proposals)

    cls_prob, bbox_pred = rnet_model.predict(rnet_input_images, verbose=0)

    face_scores = cls_prob[:, 1]
    keep_indices_cls = np.where(face_scores > cls_threshold)[0]

    if len(keep_indices_cls) == 0:
        return np.array([]), np.array([])

    filtered_proposals = valid_proposals[keep_indices_cls]
    filtered_scores = face_scores[keep_indices_cls]
    filtered_bbox_preds = bbox_pred[keep_indices_cls]

    refined_boxes = adjust_boxes(filtered_proposals, filtered_bbox_preds)

    refined_boxes = square_boxes(refined_boxes)

    refined_boxes[:, 0] = np.clip(refined_boxes[:, 0], 0, img_w - 1)
    refined_boxes[:, 1] = np.clip(refined_boxes[:, 1], 0, img_h - 1)
    refined_boxes[:, 2] = np.clip(refined_boxes[:, 2], 0, img_w - 1)
    refined_boxes[:, 3] = np.clip(refined_boxes[:, 3], 0, img_h - 1)

    keep_nms = nms(refined_boxes, filtered_scores, nms_threshold, method='union')

    final_boxes = refined_boxes[keep_nms]
    final_scores = filtered_scores[keep_nms]

    return final_boxes, final_scores

def onet_inference_function(
    image,
    onet_model,
    rnet_proposals,
    onet_input_size=(48, 48),
    cls_threshold=0.9,
    nms_threshold=0.7,
    min_face_size=20 # Minimum face size in pixels for final output
):
    """
    Performs O-Net inference on proposals generated by R-Net.

    Args:
        image: Original input image (H, W, 3) np.uint8.
        onet_model: Trained Keras O-Net model.
        rnet_proposals: Bounding box proposals from R-Net (Nx4 array).
        onet_input_size (tuple): Expected input size for O-Net (height, width).
        cls_threshold (float): Classification confidence threshold.
        nms_threshold (float): IoU threshold for NMS.
        min_face_size (int): Minimum side length for a detected face to be considered valid.

    Returns:
        tuple: Final bounding boxes (Nx4), their scores (N,), and landmark coordinates (Nx10).
    """
    if rnet_proposals.shape[0] == 0:
        return np.array([]), np.array([]), np.array([])

    img_h, img_w, _ = image.shape
    onet_input_images = []
    valid_proposals = []

    for bbox in rnet_proposals:
        x1, y1, x2, y2 = bbox.astype(int)

        x1 = np.clip(x1, 0, img_w - 1)
        y1 = np.clip(y1, 0, img_h - 1)
        x2 = np.clip(x2, 0, img_w - 1)
        y2 = np.clip(y2, 0, img_h - 1)

        if x2 <= x1 or y2 <= y1 or (x2 - x1) < min_face_size or (y2 - y1) < min_face_size:
            continue

        cropped_img = image[y1:y2, x1:x2]
        if cropped_img.shape[0] == 0 or cropped_img.shape[1] == 0:
            continue

        resized_img = cv2.resize(cropped_img, onet_input_size, interpolation=cv2.INTER_AREA)
        normalized_img = (resized_img.astype(np.float32) - 127.5) / 127.5

        onet_input_images.append(normalized_img)
        valid_proposals.append(bbox)

    if not onet_input_images:
        return np.array([]), np.array([]), np.array([])

    onet_input_images = np.array(onet_input_images)
    valid_proposals = np.array(valid_proposals)

    cls_prob, bbox_pred, landmark_pred = onet_model.predict(onet_input_images, verbose=0)

    face_scores = cls_prob[:, 1]
    keep_indices_cls = np.where(face_scores > cls_threshold)[0]

    if len(keep_indices_cls) == 0:
        return np.array([]), np.array([]), np.array([])

    filtered_proposals = valid_proposals[keep_indices_cls]
    filtered_scores = face_scores[keep_indices_cls]
    filtered_bbox_preds = bbox_pred[keep_indices_cls]
    filtered_landmark_preds = landmark_pred[keep_indices_cls]

    final_boxes = adjust_boxes(filtered_proposals, filtered_bbox_preds)

    final_boxes[:, 0] = np.clip(final_boxes[:, 0], 0, img_w - 1)
    final_boxes[:, 1] = np.clip(final_boxes[:, 1], 0, img_h - 1)
    final_boxes[:, 2] = np.clip(final_boxes[:, 2], 0, img_w - 1)
    final_boxes[:, 3] = np.clip(final_boxes[:, 3], 0, img_h - 1)

    mapped_landmarks = np.zeros_like(filtered_landmark_preds)
    for i in range(len(filtered_proposals)):
        prop_box = filtered_proposals[i]
        prop_w = prop_box[2] - prop_box[0]
        prop_h = prop_box[3] - prop_box[1]
        if prop_w > 0 and prop_h > 0:
            for k in range(5):
                mapped_landmarks[i, 2*k] = (filtered_landmark_preds[i, 2*k] / onet_input_size[0]) * prop_w + prop_box[0]
                mapped_landmarks[i, 2*k+1] = (filtered_landmark_preds[i, 2*k+1] / onet_input_size[1]) * prop_h + prop_box[1]
        else:
            mapped_landmarks[i, :] = np.zeros(10)

    keep_nms = nms(final_boxes, filtered_scores, nms_threshold, method='min')

    final_boxes = final_boxes[keep_nms]
    final_scores = filtered_scores[keep_nms]
    final_landmarks = mapped_landmarks[keep_nms]

    return final_boxes, final_scores, final_landmarks


# --- Main MTCNN Detection Function ---

def mtcnn_detect_faces(
    image,
    pnet_model,
    rnet_model,
    onet_model,
    min_face_size=20,
    scale_factor=0.709,
    pnet_cls_threshold=0.6,
    pnet_nms_threshold=0.5,
    rnet_cls_threshold=0.7,
    rnet_nms_threshold=0.7,
    onet_cls_threshold=0.9,
    onet_nms_threshold=0.7
):
    """
    Runs the full MTCNN cascaded inference pipeline on an input image.

    Args:
        image: Input image (H, W, 3) np.uint8.
        pnet_model: Trained Keras P-Net model.
        rnet_model: Trained Keras R-Net model.
        onet_model: Trained Keras O-Net model.
        min_face_size (int): Minimum size of face to detect.
        scale_factor (float): Scale factor for image pyramid.
        pnet_cls_threshold (float): Classification confidence threshold for P-Net.
        pnet_nms_threshold (float): IoU threshold for P-Net's NMS.
        rnet_cls_threshold (float): Classification confidence threshold for R-Net.
        rnet_nms_threshold (float): IoU threshold for R-Net's NMS.
        onet_cls_threshold (float): Classification confidence threshold for O-Net.
        onet_nms_threshold (float): IoU threshold for O-Net's NMS.

    Returns:
        tuple: Final bounding boxes (Nx4), their scores (N,), and landmark coordinates (Nx10).
    """

    # 1. P-Net Stage
    print("Running P-Net inference...")
    pnet_boxes, pnet_scores = pnet_inference_function(
        image,
        pnet_model,
        min_size=min_face_size,
        scale_factor=scale_factor,
        cls_threshold=pnet_cls_threshold,
        nms_threshold=pnet_nms_threshold
    )

    if pnet_boxes.shape[0] == 0:
        print("No faces detected by P-Net.")
        return np.array([]), np.array([]), np.array([])

    print(f"P-Net detected {len(pnet_boxes)} proposals. Passing to R-Net.")

    # 2. R-Net Stage
    print("Running R-Net inference...")
    rnet_boxes, rnet_scores = rnet_inference_function(
        image,
        rnet_model,
        pnet_boxes,
        cls_threshold=rnet_cls_threshold,
        nms_threshold=rnet_nms_threshold
    )

    if rnet_boxes.shape[0] == 0:
        print("No faces detected by R-Net.")
        return np.array([]), np.array([]), np.array([])

    print(f"R-Net refined to {len(rnet_boxes)} proposals. Passing to O-Net.")

    # 3. O-Net Stage
    print("Running O-Net inference...")
    final_boxes, final_scores, final_landmarks = onet_inference_function(
        image,
        onet_model,
        rnet_boxes,
        cls_threshold=onet_cls_threshold,
        nms_threshold=onet_nms_threshold,
        min_face_size=min_face_size
    )

    if final_boxes.shape[0] == 0:
        print("No faces detected by O-Net.")
        return np.array([]), np.array([]), np.array([])

    print(f"MTCNN pipeline completed. Found {len(final_boxes)} faces.")
    return final_boxes, final_scores, final_landmarks


def hard_sample_mining_onet(
    annotations,
    pnet_model,
    rnet_model,
    onet_input_size=(48, 48),
    pnet_min_size=12,
    pnet_scale_factor=0.709,
    pnet_cls_threshold=0.6,
    pnet_nms_threshold=0.5,
    rnet_cls_threshold=0.01, # Adjusted to be very lenient
    rnet_nms_threshold=0.5, # Adjusted to be more lenient
    positive_iou_threshold=0.65,
    partial_iou_threshold_low=0.4,
    partial_iou_threshold_high=0.65,
    negative_iou_threshold=0.3
):
    onet_images = []
    onet_labels = []
    onet_bbox_targets = []
    onet_landmark_targets = []

    total_images = len(annotations)
    for img_idx, img_data in enumerate(annotations):
        image_path = img_data['image_path']
        gt_boxes_orig = img_data['boxes']
        gt_landmarks_orig = img_data['landmarks']

        # Ensure ground truth boxes are in correct format (Nx4)
        if gt_boxes_orig.ndim == 1:
            gt_boxes_orig = gt_boxes_orig[np.newaxis, :]
        if gt_landmarks_orig is not None and gt_landmarks_orig.ndim == 1:
             gt_landmarks_orig = gt_landmarks_orig[np.newaxis, :]

        original_image = load_image(image_path)
        if original_image is None or original_image.size == 0:
            continue

        pnet_proposals, _ = pnet_inference_function(
            original_image,
            pnet_model,
            min_size=pnet_min_size,
            scale_factor=pnet_scale_factor,
            cls_threshold=pnet_cls_threshold,
            nms_threshold=pnet_nms_threshold
        )

        if pnet_proposals.shape[0] == 0:
            continue

        rnet_proposals, _ = rnet_inference_function(
            original_image,
            rnet_model,
            pnet_proposals,
            cls_threshold=rnet_cls_threshold, # Use adjusted threshold
            nms_threshold=rnet_nms_threshold  # Use adjusted threshold
        )

        if rnet_proposals.shape[0] == 0:
            continue

        for proposal_idx in range(rnet_proposals.shape[0]):
            prop_box = rnet_proposals[proposal_idx]

            x1_prop, y1_prop, x2_prop, y2_prop = prop_box.astype(int)
            prop_w = x2_prop - x1_prop
            prop_h = y2_prop - y1_prop

            if prop_w <= 0 or prop_h <= 0:
                continue
            if x1_prop < 0 or y1_prop < 0 or x2_prop > original_image.shape[1] or y2_prop > original_image.shape[0]:
                continue

            cropped_img_patch = original_image[y1_prop:y2_prop, x1_prop:x2_prop].copy()
            if cropped_img_patch.shape[0] == 0 or cropped_img_patch.shape[1] == 0:
                continue

            resized_patch = cv2.resize(cropped_img_patch, onet_input_size, interpolation=cv2.INTER_AREA)
            normalized_patch = (resized_patch.astype(np.float32) - 127.5) / 127.5

            max_iou_val = 0.0
            best_gt_box_idx = -1
            if len(gt_boxes_orig) > 0: # Check if there are ground truth boxes to compare against
                ious = iou(prop_box, gt_boxes_orig)
                max_iou_val = np.max(ious)
                best_gt_box_idx = np.argmax(ious)

            label = -2
            bbox_target = np.zeros(4)
            landmark_target = np.zeros(10)

            if max_iou_val >= positive_iou_threshold: # Positive sample
                label = 1
                best_gt_box = gt_boxes_orig[best_gt_box_idx]
                bbox_target = bbox_regression_target(np.array([prop_box]), np.array([best_gt_box]))[0]

                if gt_landmarks_orig is not None and len(gt_landmarks_orig) > 0:
                    gt_landmark = gt_landmarks_orig[best_gt_box_idx]
                    current_prop_w = prop_box[2] - prop_box[0]
                    current_prop_h = prop_box[3] - prop_box[1]

                    if current_prop_w > 0 and current_prop_h > 0:
                        normalized_landmark = np.zeros_like(gt_landmark, dtype=np.float32)
                        for k in range(5):
                            normalized_landmark[2*k] = (gt_landmark[2*k] - prop_box[0]) * (onet_input_size[0] / current_prop_w)
                            normalized_landmark[2*k+1] = (gt_landmark[2*k+1] - prop_box[1]) * (onet_input_size[1] / current_prop_h)
                        landmark_target = normalized_landmark

                onet_images.append(normalized_patch)
                onet_labels.append(label)
                onet_bbox_targets.append(bbox_target)
                onet_landmark_targets.append(landmark_target)

            elif max_iou_val >= partial_iou_threshold_low and max_iou_val < partial_iou_threshold_high: # Partial sample
                label = -1
                best_gt_box = gt_boxes_orig[best_gt_box_idx]
                bbox_target = bbox_regression_target(np.array([prop_box]), np.array([best_gt_box]))[0]

                onet_images.append(normalized_patch)
                onet_labels.append(label)
                onet_bbox_targets.append(bbox_target)
                onet_landmark_targets.append(np.zeros(10)) # No landmark loss for partial

            elif max_iou_val < negative_iou_threshold:
                label = 0

                onet_images.append(normalized_patch)
                onet_labels.append(label)
                onet_bbox_targets.append(np.zeros(4))
                onet_landmark_targets.append(np.zeros(10)) # No landmark loss for negatives

    # Ensure empty arrays have correct 2D shape if no samples were collected
    onet_images_np = np.array(onet_images)
    onet_labels_np = np.array(onet_labels)

    if not onet_bbox_targets:
        onet_bbox_targets_np = np.empty((0, 4), dtype=np.float32)
    else:
        onet_bbox_targets_np = np.array(onet_bbox_targets)

    if not onet_landmark_targets:
        onet_landmark_targets_np = np.empty((0, 10), dtype=np.float32)
    else:
        onet_landmark_targets_np = np.array(onet_landmark_targets)

    return (
        onet_images_np,
        onet_labels_np,
        onet_bbox_targets_np,
        onet_landmark_targets_np
    )

def hard_sample_mining_rnet(
    annotations,
    pnet_model,
    rnet_input_size=(24, 24),
    pnet_min_size=12,
    pnet_scale_factor=0.709,
    pnet_cls_threshold=0.6,
    pnet_nms_threshold=0.5,
    positive_iou_threshold=0.65,
    partial_iou_threshold_low=0.4,
    partial_iou_threshold_high=0.65,
    negative_iou_threshold=0.3
):
    """
    Performs hard sample mining for R-Net training.

    Args:
        annotations (list): List of dictionaries, each containing 'image_path', 'boxes'.
        pnet_model: Trained Keras P-Net model.
        rnet_input_size (tuple): Expected input size for R-Net (height, width).
        pnet_min_size (int): Minimum face size for P-Net detection.
        pnet_scale_factor (float): Scale factor for P-Net image pyramid.
        pnet_cls_threshold (float): Classification confidence threshold for P-Net proposals.
        pnet_nms_threshold (float): IoU threshold for P-Net's NMS.
        positive_iou_threshold (float): IoU >= this to be a positive sample.
        partial_iou_threshold_low (float): IoU >= this to be a partial sample.
        partial_iou_threshold_high (float): IoU < this to be a partial sample.
        negative_iou_threshold (float): IoU < this to be a hard negative sample.

    Returns:
        tuple: Lists of collected hard samples (images, labels, bbox_targets) for R-Net.
    """

    rnet_images = []
    rnet_labels = []
    rnet_bbox_targets = []

    total_images = len(annotations)
    for img_idx, img_data in enumerate(annotations):
        image_path = img_data['image_path']
        gt_boxes_orig = img_data['boxes'] # Ground truth boxes in original image coordinates

        print(f"Processing image {img_idx + 1}/{total_images}: {image_path}")

        # 1. Load the image
        original_image = load_image(image_path)
        if original_image is None or original_image.size == 0:
            print(f"Warning: Could not load image {image_path}. Skipping.")
            continue

        # 2. Run P-Net inference to obtain candidate face proposals
        pnet_proposals, pnet_scores = pnet_inference_function(
            original_image,
            pnet_model,
            min_size=pnet_min_size,
            scale_factor=pnet_scale_factor,
            cls_threshold=pnet_cls_threshold,
            nms_threshold=pnet_nms_threshold
        )

        if pnet_proposals.shape[0] == 0:
            print(f"No proposals from P-Net for {image_path}. Skipping to next image.")
            continue

        # 3. Classify P-Net proposals based on IoU with ground truth
        for proposal_idx in range(pnet_proposals.shape[0]):
            prop_box = pnet_proposals[proposal_idx]

            # Ensure proposal box is valid before cropping
            x1_prop, y1_prop, x2_prop, y2_prop = prop_box.astype(int)
            prop_w = x2_prop - x1_prop
            prop_h = y2_prop - y1_prop

            if prop_w <= 0 or prop_h <= 0:
                continue
            if x1_prop < 0 or y1_prop < 0 or x2_prop > original_image.shape[1] or y2_prop > original_image.shape[0]:
                continue # Skip if proposal is out of bounds (should be clipped by pnet_inference_function, but good to check)

            cropped_img_patch = original_image[y1_prop:y2_prop, x1_prop:x2_prop].copy()
            if cropped_img_patch.shape[0] == 0 or cropped_img_patch.shape[1] == 0:
                continue

            resized_patch = cv2.resize(cropped_img_patch, rnet_input_size, interpolation=cv2.INTER_AREA)
            normalized_patch = (resized_patch.astype(np.float32) - 127.5) / 127.5

            max_iou_val = 0.0
            best_gt_box = None
            if len(gt_boxes_orig) > 0:
                ious = iou(prop_box, gt_boxes_orig)
                max_iou_val = np.max(ious)
                best_gt_box_idx = np.argmax(ious)
                best_gt_box = gt_boxes_orig[best_gt_box_idx]

            label = -2 # Initialize as ignored
            bbox_target = np.zeros(4)

            if max_iou_val >= positive_iou_threshold: # Positive sample
                label = 1
                bbox_target = bbox_regression_target(np.array([prop_box]), np.array([best_gt_box]))[0]
                # Store sample
                rnet_images.append(normalized_patch)
                rnet_labels.append(label)
                rnet_bbox_targets.append(bbox_target)

            elif max_iou_val >= partial_iou_threshold_low and max_iou_val < partial_iou_threshold_high: # Partial sample
                label = -1 # Indicate partial for regression, ignored for classification
                bbox_target = bbox_regression_target(np.array([prop_box]), np.array([best_gt_box]))[0]
                # Store sample
                rnet_images.append(normalized_patch)
                rnet_labels.append(label)
                rnet_bbox_targets.append(bbox_target)

            elif max_iou_val < negative_iou_threshold: # Hard Negative sample
                label = 0 # Non-face label
                # Store sample
                rnet_images.append(normalized_patch)
                rnet_labels.append(label)
                rnet_bbox_targets.append(bbox_target) # Bbox targets are zeros for negatives

    print(f"Finished hard sample mining. Total R-Net samples collected: {len(rnet_images)}")
    return np.array(rnet_images), np.array(rnet_labels), np.array(rnet_bbox_targets)
